name: CI

on:
  push:
    branches: [ run_test ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS deps
        run: yarn install --frozen-lockfile || yarn install

      - name: Prepare DB (sqlite or pg if configured)
        run: bin/rails db:prepare

      - name: RuboCop
        run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt

      - name: Brakeman
        run: bundle exec brakeman -q -w2 -o brakeman.json || true

      - name: RSpec
        run: bundle exec rspec --format documentation --out rspec.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            rubocop.txt
            brakeman.json
            rspec.txt
            coverage/
